"""initial migration

Revision ID: 618542cb877e
Revises: 
Create Date: 2026-06-10 17:11:53.880960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '618542cb877e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('text_patterns', sa.JSON(), nullable=False),
    sa.Column('min_pages', sa.Integer(), nullable=False),
    sa.Column('max_pages', sa.Integer(), nullable=False),
    sa.Column('visual_hints', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processing_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('source_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'failed', 'needs_review', name='job_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('output_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('document_type_id', sa.String(), nullable=False),
    sa.Column('occurrence_index', sa.Integer(), nullable=False),
    sa.Column('start_page', sa.Integer(), nullable=False),
    sa.Column('end_page', sa.Integer(), nullable=False),
    sa.Column('output_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ok', 'needs_review', 'error', name='output_doc_status'), nullable=False),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('document_type_id', sa.String(), nullable=True),
    sa.Column('detection_method', sa.Enum('text_layer', 'fusion', 'vlm', 'manual', name='detection_method'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('is_title_page', sa.Boolean(), nullable=False),
    sa.Column('manual_override', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page_results')
    op.drop_table('output_documents')
    op.drop_table('processing_jobs')
    op.drop_table('document_types')
    # ### end Alembic commands ###
